### ISSUE TITLE
http://localhost:7071/api/post

### ISSUE THREAD

**Issue by Jens-Wymeersch** [craigshoemaker/html-css-javascript-getting-started#3]
Dear Craig,

I've enjoyed your course on Pluralsight. One item I didn't understand or found out was how to setup http://localhost:7071/api/post. Can you please advice ?

Regards,
Jens

**Comment by craigshoemaker** [comment]
Hi, @Jens-Wymeersch! Check out this repository: https://github.com/craigshoemaker/echo-post
